name: Build and Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build
      
    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/emplate-asset-transfer
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    # - name: Deploy via FTP
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: ./dist/your-app-name/
    #     server-dir: /public_html/
        
    # Alternative: Deploy to AWS S3
    # - name: Deploy to S3
    #   uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     SOURCE_DIR: './dist/your-app-name'